import type { HealthyAlternativeCategory } from "./types";

export const healthyAlternativeCategories: HealthyAlternativeCategory[] = [
  {
    id: "bread-bakery",
    slug: "bread-bakery",
    name: "Bread & Bakery",
    description: "Better options for breads, wraps and everyday bakery staples.",
    order: 1,
  },
  {
    id: "breakfast",
    slug: "breakfast",
    name: "Breakfast",
    description: "Better options for cereals, oats and morning staples.",
    order: 2,
  },
  {
    id: "dairy",
    slug: "dairy",
    name: "Dairy",
    description: "Better options for milk, yogurt, cheese and dairy basics.",
    order: 3,
  },
  {
    id: "eggs",
    slug: "eggs",
    name: "Eggs",
    description: "Better options for everyday eggs and egg products.",
    order: 4,
  },
  {
    id: "meat",
    slug: "meat",
    name: "Meat",
    description: "Better options for beef, poultry, pork and prepared meats.",
    order: 5,
  },
  {
    id: "seafood",
    slug: "seafood",
    name: "Seafood",
    description: "Better options for fish, shellfish and seafood staples.",
    order: 6,
  },
  {
    id: "snacks",
    slug: "snacks",
    name: "Snacks",
    description: "Better options for chips, crackers, bars and snack foods.",
    order: 7,
  },
  {
    id: "drinks",
    slug: "drinks",
    name: "Drinks",
    description: "Better options for everyday beverages.",
    order: 8,
  },
  {
    id: "sauces-condiments",
    slug: "sauces-condiments",
    name: "Sauces & Condiments",
    description: "Better options for sauces, spreads, dressings and condiments.",
    order: 9,
  },
  {
    id: "frozen-foods",
    slug: "frozen-foods",
    name: "Frozen Foods",
    description: "Better options for frozen meals, sides and freezer staples.",
    order: 10,
  },
  {
    id: "rice-pasta",
    slug: "rice-pasta",
    name: "Rice & Pasta",
    description: "Better options for rice, pasta and pantry grain staples.",
    order: 11,
  },
  {
    id: "cooking-oils",
    slug: "cooking-oils",
    name: "Cooking Oils",
    description: "Better options for cooking fats and everyday oils.",
    order: 12,
  },
  {
    id: "chocolate-sweets",
    slug: "chocolate-sweets",
    name: "Chocolate & Sweets",
    description: "Better options for chocolate, candy and sweet treats.",
    order: 13,
  },
  {
    id: "baby-kids-foods",
    slug: "baby-kids-foods",
    name: "Baby & Kids Foods",
    description: "Better options for baby food and family-friendly staples.",
    order: 14,
  },
  {
    id: "plant-based-alternatives",
    slug: "plant-based-alternatives",
    name: "Plant-Based Alternatives",
    description: "Better options for plant-based swaps and meat-free staples.",
    order: 15,
  },
];
