import type { HealthyAlternativeProduct } from "./types";

const demoSource = {
  kind: "demo",
  note: "Temporary Healthy Alternatives demo data for layout and helper testing only.",
} as const;

export const healthyAlternativeDemoProducts: HealthyAlternativeProduct[] = [
  {
    id: "demo-sprouted-buckwheat-sourdough",
    slug: "demo-sprouted-buckwheat-sourdough",
    productName: "Demo Sprouted Buckwheat Sourdough",
    brand: "Demo Hearth",
    category: "Bread & Bakery",
    subcategory: "Bread",
    productType: "Sourdough Bread",
    shortDescription:
      "A simple demo bread option with a short ingredient list and no seed oils.",
    whyRecommended:
      "Selected as demo data for its simple formulation and clear recommendation tags.",
    recommendationTags: [
      "Best Overall",
      "Simple Ingredients",
      "Seed Oil Free",
      "Gluten Free",
      "Organic",
      "Few Ingredients",
    ],
    ingredients: ["Sprouted buckwheat", "Sea salt"],
    ingredientCount: 2,
    processingLevel: { group: 3, label: "Processed" },
    keyBenefits: ["Short ingredient list", "No seed oils", "Gluten free"],
    thingsToKnow: ["Demo record only", "Still a packaged processed food"],
    dietaryTags: ["Gluten Free", "Organic"],
    packageSize: "13 oz",
    amazon: {
      asin: "DEMOALT001",
      url: "https://www.amazon.com/dp/DEMOALT001",
      affiliateUrl: null,
    },
    images: {
      primary: "/alternatives/demo/sprouted-buckwheat-front.png",
      gallery: [
        "/alternatives/demo/sprouted-buckwheat-front.png",
        "/alternatives/demo/sprouted-buckwheat-side.png",
      ],
    },
    selection: {
      recommended: true,
      rank: 1,
      reason: "Strong demo bread alternative.",
    },
    alternativeForMarkers: ["seedOils", "artificialPreservatives"],
    replaces: ["packaged-bread", "sourdough-bread"],
    source: demoSource,
  },
  {
    id: "demo-short-list-oat-cereal",
    slug: "demo-short-list-oat-cereal",
    productName: "Demo Short List Oat Cereal",
    brand: "Demo Morning",
    category: "Breakfast",
    subcategory: "Cereal",
    productType: "Breakfast Cereal",
    shortDescription:
      "A demo cereal record for testing one-image products and simple tags.",
    whyRecommended:
      "Selected as demo data for a short ingredient list and lower-sugar positioning.",
    recommendationTags: ["Simple Ingredients", "Lower Sugar"],
    ingredients: ["Whole grain oats", "Sea salt"],
    ingredientCount: 2,
    processingLevel: { group: 3, label: "Processed" },
    keyBenefits: ["Simple ingredient list", "Lower sugar demo option"],
    thingsToKnow: ["Demo record only"],
    dietaryTags: ["Whole Grain"],
    packageSize: "10 oz",
    images: {
      primary: "/alternatives/demo/oat-cereal.png",
      gallery: [],
    },
    selection: {
      recommended: true,
      rank: 2,
      reason: "Simple demo breakfast alternative.",
    },
    alternativeForMarkers: ["highSugar"],
    replaces: ["breakfast-cereal"],
    source: demoSource,
  },
  {
    id: "demo-plain-grass-fed-yogurt",
    slug: "demo-plain-grass-fed-yogurt",
    productName: "Demo Plain Grass-Fed Yogurt",
    brand: "Demo Valley",
    category: "Dairy",
    subcategory: "Yogurt",
    productType: "Greek Yogurt",
    shortDescription:
      "A plain demo yogurt option for testing dairy category records.",
    whyRecommended:
      "Selected as demo data for plain ingredients and no added sweeteners.",
    recommendationTags: ["Grass Fed", "No Added Sugar", "Simple Ingredients"],
    ingredients: ["Cultured milk"],
    ingredientCount: 1,
    processingLevel: { group: 3, label: "Processed" },
    keyBenefits: ["One ingredient", "No added sugar"],
    thingsToKnow: ["Contains dairy", "Demo record only"],
    dietaryTags: ["Vegetarian"],
    packageSize: "24 oz",
    amazon: {
      asin: "DEMOALT002",
      url: "https://www.amazon.com/dp/DEMOALT002",
      affiliateUrl: "https://www.amazon.com/dp/DEMOALT002?tag=demo",
    },
    images: {
      primary: "/alternatives/demo/plain-yogurt.png",
    },
    selection: {
      recommended: true,
      rank: 3,
      reason: "Plain demo dairy alternative.",
    },
    alternativeForMarkers: ["addedSugar", "artificialSweeteners"],
    replaces: ["sweetened-yogurt"],
    source: demoSource,
  },
  {
    id: "demo-pasture-raised-eggs",
    slug: "demo-pasture-raised-eggs",
    productName: "Demo Pasture-Raised Eggs",
    brand: "Demo Nest",
    category: "Eggs",
    subcategory: "Eggs",
    productType: "Eggs",
    shortDescription:
      "A demo egg record with minimal tags for testing compact cards later.",
    whyRecommended: "Selected as demo data for simple egg category coverage.",
    recommendationTags: ["Pasture Raised"],
    ingredients: ["Eggs"],
    ingredientCount: 1,
    keyBenefits: ["Single ingredient"],
    thingsToKnow: ["Contains egg", "Demo record only"],
    dietaryTags: ["Vegetarian"],
    packageSize: "12 count",
    selection: {
      recommended: true,
      rank: 4,
      reason: "Simple demo egg alternative.",
    },
    replaces: ["eggs"],
    source: demoSource,
  },
  {
    id: "demo-wild-salmon-fillets",
    slug: "demo-wild-salmon-fillets",
    productName: "Demo Wild Salmon Fillets",
    brand: "Demo Tide",
    category: "Seafood",
    subcategory: "Salmon",
    productType: "Frozen Salmon",
    shortDescription:
      "A demo seafood option for testing wild-caught recommendation tags.",
    whyRecommended:
      "Selected as demo data for a seafood alternative with a short ingredient list.",
    recommendationTags: ["Wild Caught", "Simple Ingredients"],
    ingredients: ["Salmon"],
    ingredientCount: 1,
    keyBenefits: ["One ingredient", "Wild-caught demo marker"],
    thingsToKnow: ["Contains fish", "Demo record only"],
    dietaryTags: ["Pescatarian"],
    packageSize: "12 oz",
    images: {
      primary: "/alternatives/demo/wild-salmon.png",
    },
    selection: {
      recommended: true,
      rank: 1,
      reason: "Strong demo seafood alternative.",
    },
    alternativeForMarkers: ["phosphates"],
    replaces: ["frozen-salmon", "seafood"],
    source: demoSource,
  },
  {
    id: "demo-seed-oil-free-potato-chips",
    slug: "demo-seed-oil-free-potato-chips",
    productName: "Demo Seed-Oil-Free Potato Chips",
    brand: "Demo Crunch",
    category: "Snacks",
    subcategory: "Chips",
    productType: "Potato Chips",
    shortDescription:
      "A demo snack option for testing chip alternatives and Amazon links.",
    whyRecommended:
      "Selected as demo data for a snack alternative without seed oils.",
    recommendationTags: ["Seed Oil Free", "Simple Ingredients"],
    ingredients: ["Potatoes", "Avocado oil", "Sea salt"],
    ingredientCount: 3,
    processingLevel: { group: 3, label: "Processed" },
    keyBenefits: ["No seed oils", "Short ingredient list"],
    thingsToKnow: ["Still a salty snack", "Demo record only"],
    dietaryTags: ["Gluten Free", "Vegan"],
    packageSize: "5 oz",
    amazon: {
      asin: "DEMOALT003",
      url: "https://www.amazon.com/dp/DEMOALT003",
      affiliateUrl: null,
    },
    images: {
      primary: "/alternatives/demo/potato-chips.png",
    },
    selection: {
      recommended: true,
      rank: 1,
      reason: "Strong demo snack alternative.",
    },
    alternativeForMarkers: ["seedOils"],
    replaces: ["potato-chips", "packaged-snacks"],
    source: demoSource,
  },
  {
    id: "demo-lower-sugar-ketchup",
    slug: "demo-lower-sugar-ketchup",
    productName: "Demo Lower Sugar Ketchup",
    brand: "Demo Table",
    category: "Sauces & Condiments",
    subcategory: "Ketchup",
    productType: "Ketchup",
    shortDescription:
      "A demo condiment option for testing sauce and condiment records.",
    whyRecommended:
      "Selected as demo data for lower-sugar positioning and simple ingredients.",
    recommendationTags: ["Lower Sugar", "No Artificial Colors"],
    ingredients: ["Tomato puree", "Vinegar", "Date paste", "Sea salt", "Spices"],
    ingredientCount: 5,
    processingLevel: { group: 3, label: "Processed" },
    keyBenefits: ["Lower sugar demo option", "No artificial colors"],
    thingsToKnow: ["Demo record only"],
    dietaryTags: ["Vegan"],
    packageSize: "12 oz",
    images: {
      primary: "/alternatives/demo/lower-sugar-ketchup.png",
    },
    selection: {
      recommended: true,
      rank: 2,
      reason: "Useful demo condiment alternative.",
    },
    alternativeForMarkers: ["highFructoseCornSyrup", "artificialColors"],
    replaces: ["ketchup", "condiments"],
    source: demoSource,
  },
  {
    id: "demo-brown-rice-pasta",
    slug: "demo-brown-rice-pasta",
    productName: "Demo Brown Rice Pasta",
    brand: "Demo Pantry",
    category: "Rice & Pasta",
    subcategory: "Pasta",
    productType: "Pasta",
    shortDescription:
      "A demo pasta option intentionally missing ingredient details.",
    whyRecommended:
      "Selected as demo data to test missing ingredient handling safely.",
    recommendationTags: ["Gluten Free"],
    keyBenefits: ["Missing ingredient test case"],
    thingsToKnow: ["Ingredients intentionally unavailable in demo data"],
    dietaryTags: ["Gluten Free"],
    packageSize: "16 oz",
    selection: {
      recommended: true,
      rank: 5,
      reason: "Demo product for missing ingredient states.",
    },
    replaces: ["pasta"],
    source: demoSource,
  },
  {
    id: "demo-extra-virgin-olive-oil",
    slug: "demo-extra-virgin-olive-oil",
    productName: "Demo Extra Virgin Olive Oil",
    brand: "Demo Grove",
    category: "Cooking Oils",
    subcategory: "Olive Oil",
    productType: "Cooking Oil",
    shortDescription:
      "A demo cooking oil option for testing oil category alternatives.",
    whyRecommended:
      "Selected as demo data for a cooking oil alternative to seed oils.",
    recommendationTags: ["Seed Oil Free", "Simple Ingredients"],
    ingredients: ["Extra virgin olive oil"],
    ingredientCount: 1,
    keyBenefits: ["One ingredient", "Seed oil free"],
    thingsToKnow: ["Demo record only"],
    dietaryTags: ["Vegan"],
    packageSize: "500 ml",
    images: {
      primary: "/alternatives/demo/olive-oil.png",
    },
    selection: {
      recommended: true,
      rank: 1,
      reason: "Strong demo cooking oil alternative.",
    },
    alternativeForMarkers: ["seedOils"],
    replaces: ["cooking-oils"],
    source: demoSource,
  },
  {
    id: "demo-dark-chocolate-squares",
    slug: "demo-dark-chocolate-squares",
    productName: "Demo Dark Chocolate Squares",
    brand: "Demo Cocoa",
    category: "Chocolate & Sweets",
    subcategory: "Chocolate",
    productType: "Dark Chocolate",
    shortDescription:
      "A demo sweet option for testing dessert alternatives and multiple tags.",
    whyRecommended:
      "Selected as demo data for a shorter sweet-treat ingredient list.",
    recommendationTags: [
      "Lower Sugar",
      "Simple Ingredients",
      "No Artificial Colors",
      "No Artificial Sweeteners",
    ],
    ingredients: ["Cocoa mass", "Cocoa butter", "Coconut sugar", "Vanilla"],
    ingredientCount: 4,
    processingLevel: { group: 3, label: "Processed" },
    keyBenefits: ["No artificial colors", "No artificial sweeteners"],
    thingsToKnow: ["Still a sweet treat", "Demo record only"],
    dietaryTags: ["Vegan"],
    packageSize: "3 oz",
    amazon: {
      asin: "DEMOALT004",
      url: "https://www.amazon.com/dp/DEMOALT004",
      affiliateUrl: null,
    },
    images: {
      primary: "/alternatives/demo/dark-chocolate.png",
    },
    selection: {
      recommended: true,
      rank: 2,
      reason: "Useful demo sweet alternative.",
    },
    alternativeForMarkers: ["artificialColors", "artificialSweeteners"],
    replaces: ["chocolate", "sweets"],
    source: demoSource,
  },
];

export const healthyAlternativeProducts = healthyAlternativeDemoProducts;
